kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-data-store-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
