apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: aws-load-balancer-controller
  name: {{ .Release.Name }}-{{ .Values.serviceAccount.name }}
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::538578370230:role/AmazonEKSLoadBalancerControllerRole
