{{- range list .Values.newsread-dep .Values.hello-world-dep -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
  labels:
    app: {{ .labels.app }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{ .matchLabels.app }}
  template:
    metadata:
      labels:
        {{ .template.labels.app }}
    spec:
      containers:
        - name: {{ .containers.name }}
          image: "{{ .containers.image.repository }}:{{ .containers.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .ports }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          {{- if .env }}
          env:
            - name: {{ .env.name }}
              value: {{ .env.value }}
          {{- end }}
          {{- if .envFrom }}
          envFrom:
            secretkeyRef:
              name: {{ .envFrom.name }}
              optional: {{ .envFrom.optional }}
          {{- end }}
{{ end -}}
