{{- range list .Values.newsread -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
  labels:
    app: {{ .labels.app }}
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      app: {{ .matchLabels.app }}
  template:
    metadata:
      labels:
        app: {{ .template.labels.app }}
    spec:
      containers:
        - name: {{ .containers.name }}
          image: "{{ .containers.image.repository }}:{{ .containers.image.tag }}"
          imagePullPolicy: Always
          {{- if .ports }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          {{- end }}
          {{- if .env }}
          env:
            - name: {{ .env.name }}
              value: {{ .env.value }}
          {{- end }}
          {{- if .envFrom }}
          envFrom:
          - secretRef:
              name: {{ $.Release.Name }}-{{ .envFrom.name }}
              optional: {{ .envFrom.optional }}
          {{- end }}
{{ end -}}
