apiVersion: v1
kind: Service
metadata:
  labels:
    name: hello-world
  name: hello-world
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-world
  type: NodePort
