apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.name }}-ingress-demo
spec:
  ingressClassName: aws-ingress
  rules:
    - host: test.ingress-demo.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ Release.Name }}-newsread
                port:
                  number: 80
          - path: /hello
            pathType: Prefix
            backend:
              service:
                name: {{ Release.Name }}-hello-world
                port:
                  number: 80
