apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-demo
spec:
  ingressClassName: aws-ingress
  rules:
    - host: test.ingress-demo.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: newsread
                port:
                  number: 80
          - path: /hello
            pathType: Prefix
            backend:
              service:
                name: hello-world
                port:
                  number: 80
