{{- range list .Values.statefulsetservice -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name}}-{{ .name }}
  {{- if .labels.name }}
  labels:
    name: {{ .labels.name }}
  {{- else if .labels.app }}
  labels:
    app: {{ .labels.app }}
  {{- end }}
spec:
  {{- if .type }}
  type: {{ .type }}
  {{- end }}
  ports:
    - port: {{ .port }}
      {{ if .targetPort }}
      targetPort: {{ .targetPort }}
      {{- end }}
      protocol: TCP
      name: http
  selector:
    app: {{ .selector.app }}
  {{- if .clusterIP }}
  clusterIP: {{ .clusterIP }}
  {{- end }}
{{ end -}}
