apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: default
  name: {{ .Release.Name }}-mysql
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql
  replicas: {{ .Values.statefulset.replicaCount }}
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: database-vol
          mountPath: /var/lib/mysql
        envFrom:
         - secretRef:
             name: my-secrets
             optional: false
        ports:
        - containerPort: 3306
      volumes:
      - name: database-vol
        persistentVolumeClaim:
          claimName: mysql-data-store-pvc
